[build]
  command = "php -S localhost:8000"
  publish = ""

[build.environment]
  PHP_VERSION = "8.1"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[headers]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Strict-Transport-Security = "max-age=31536000; includeSubDomains"
      Referrer-Policy = "strict-origin-when-cross-origin"
